In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.03715954,  0.1853282 ,  0.14790036,  0.0730052 ,  0.01252517,
         0.01044014, -0.17652385,  0.72119576, -0.13899061, -0.04004645]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.09245335, 0.10721893, 0.10328013, 0.09582751, 0.09020364,
        0.09001576, 0.0746657 , 0.18322967, 0.07752141, 0.08558398]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.4077706)

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9785 - loss: 0.0657
Epoch 2/100
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9810 - loss: 0.0589
Epoch 3/100
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9834 - loss: 0.0516
Epoch 4/100
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - accuracy: 0.9857 - loss: 0.0444
Epoch 5/100
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9862 - loss: 0.0402
Epoch 6/100
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9867 - loss: 0.0397
Epoch 7/100
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9864 - loss: 0.0392
Epoch 8/100
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9882 - loss: 0.0352
Epoch 9/100
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9881 - loss: 0.0339
Epoch 10/100
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9900 - loss: 0.0304
Epoch 11/100
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9890 - loss: 0.0320
Epoch 12/100
1

In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9815 - loss: 0.1660


[0.16595007479190826, 0.9815000295639038]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.4065029e-21, 4.6930437e-23, 1.1552607e-21, 3.5360093e-11,
        2.5543603e-29, 2.6801368e-20, 0.0000000e+00, 1.0000000e+00,
        2.8525816e-17, 2.8673016e-15],
       [0.0000000e+00, 5.3984643e-24, 1.0000000e+00, 2.8635394e-24,
        0.0000000e+00, 2.6398865e-33, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [5.0121142e-31, 1.0000000e+00, 4.1580827e-12, 5.0985960e-19,
        1.3984712e-13, 9.2895698e-17, 5.1010888e-18, 2.2775161e-12,
        3.0837577e-10, 9.6246844e-24],
       [1.0000000e+00, 6.3531397e-38, 1.2925272e-15, 3.5020448e-27,
        4.7556930e-28, 4.3624371e-21, 1.9530299e-19, 3.2316546e-27,
        5.0535668e-30, 8.1188100e-25],
       [1.2853712e-18, 0.0000000e+00, 2.6684383e-18, 3.0703221e-26,
        1.0000000e+00, 9.9202190e-22, 1.2607461e-17, 3.4426776e-12,
        4.5447016e-22, 4.4206021e-09]], dtype=float32)>